version: '3.8'

services:
  eurekaserver:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false

  apigateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  shareddtos:
    build:
      context: ./shared-dtos
      dockerfile: Dockerfile
    container_name: shareddtos

  authservice:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolUser
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  cartservice:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cartservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolCart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  categoryservice:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    container_name: categoryservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolCategory
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  orderservice:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: orderservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolOrder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  productservice:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: productservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolProduct
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  stockservice:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: stockservice
    depends_on:
      - shareddtos
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/friendyolStock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka