server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**

        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stock/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
